# Generated by Django 5.2.4 on 2025-07-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_name',
            field=models.CharField(default='unknoen', max_length=100),
        ),
    ]
