# Generated by Django 5.2.4 on 2025-07-17 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='likes',
        ),
        migrations.AddField(
            model_name='task',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='liked_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
