# Generated by Django 5.2.4 on 2025-07-17 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_tag'),
        ('todo', '0003_remove_task_likes_task_liked_users'),
    ]

    operations = [
    ]
