# Generated by Django 5.2.3 on 2025-07-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_user_name'),
        ('todo', '0004_merge_20250717_1610'),
    ]

    operations = [
    ]
